// Code generated by MockGen. DO NOT EDIT.
// Source: generaltypes.go

// Package types is a generated GoMock package.
package types

import (
	"context"
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockAIClient is a mock of AIClient interface.
type MockAIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAIClientMockRecorder
}

// MockAIClientMockRecorder is the mock recorder for MockAIClient.
type MockAIClientMockRecorder struct {
	mock *MockAIClient
}

// NewMockAIClient creates a new mock instance.
func NewMockAIClient(ctrl *gomock.Controller) *MockAIClient {
	mock := &MockAIClient{ctrl: ctrl}
	mock.recorder = &MockAIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIClient) EXPECT() *MockAIClientMockRecorder {
	return m.recorder
}

// CreateChatCompletion mocks base method.
func (m *MockAIClient) CreateChatCompletion(ctx context.Context, msgs []*ThreadMessage) (*ThreadMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatCompletion", ctx, msgs)
	ret0, _ := ret[0].(*ThreadMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChatCompletion indicates an expected call of CreateChatCompletion.
func (mr *MockAIClientMockRecorder) CreateChatCompletion(ctx, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatCompletion", reflect.TypeOf((*MockAIClient)(nil).CreateChatCompletion), ctx, msgs)
}

// StreamChatCompletion mocks base method.
func (m *MockAIClient) StreamChatCompletion(ctx context.Context, msgs []*ThreadMessage) (*StreamResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChatCompletion", ctx, msgs)
	ret0, _ := ret[0].(*StreamResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamChatCompletion indicates an expected call of StreamChatCompletion.
func (mr *MockAIClientMockRecorder) StreamChatCompletion(ctx, msgs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChatCompletion", reflect.TypeOf((*MockAIClient)(nil).StreamChatCompletion), ctx, msgs)
}

// SetReasoning mocks base method.
func (m *MockAIClient) SetReasoning(level ReasoningEffort) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReasoning", level)
}

// SetReasoning indicates an expected call of SetReasoning.
func (mr *MockAIClientMockRecorder) SetReasoning(level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReasoning", reflect.TypeOf((*MockAIClient)(nil).SetReasoning), level)
}

// SubscribeProgress mocks base method.
func (m *MockAIClient) SubscribeProgress(invocationID string) chan ProgressEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeProgress", invocationID)
	ret0, _ := ret[0].(chan ProgressEvent)
	return ret0
}

// SubscribeProgress indicates an expected call of SubscribeProgress.
func (mr *MockAIClientMockRecorder) SubscribeProgress(invocationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeProgress", reflect.TypeOf((*MockAIClient)(nil).SubscribeProgress), invocationID)
}

// UnsubscribeProgress mocks base method.
func (m *MockAIClient) UnsubscribeProgress(ch chan ProgressEvent, invocationID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnsubscribeProgress", ch, invocationID)
}

// UnsubscribeProgress indicates an expected call of UnsubscribeProgress.
func (mr *MockAIClientMockRecorder) UnsubscribeProgress(ch, invocationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeProgress", reflect.TypeOf((*MockAIClient)(nil).UnsubscribeProgress), ch, invocationID)
}
